[package]
name = "gpengine"
version = "0.1.0"
authors = ["DanielVisser"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.24.0"
ash = "0.32.0"
ash-window = "0.6"